name: build-ios-simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios-simulator:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Install Flutter dependencies
      run: flutter pub get

    # Her hoppet vi over 'flutter analyze' for å unngå formateringskrøll!

    - name: Install Pods
      run: |
        cd ios
        pod install
        cd ..

    - name: Build Unsigned iOS Simulator App
      run: |
        flutter build ios --simulator --no-codesign

    # Pakk om til Payload med riktig struktur for Sideloadly
    - name: Prepare App for Sideloading
      run: |
        mkdir -p build/ios/iphoneos/Payload
        cp -r build/ios/iphonesimulator/Runner.app build/ios/iphoneos/Payload/
        cd build/ios/iphoneos
        zip -r Runner.ipa Payload

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Runner-IPA
        path: build/ios/iphoneos/Runner.ipa
        retention-days: 5



